"""This python file will handle some extra functions."""
import json
import sys
import threading
from os.path import exists

import yaml
from playsound import playsound
from yaml import SafeLoader


def config_file_generator():
    """Generate the template of config file"""
    with open('config.yml', 'w', encoding="utf8") as f:
        f.write("""# ++--------------------------------++
# | MiramarTicketBot                 |
# | Made by LD (MIT License)         |
# ++--------------------------------++

# NOTES:
# If any ding sound is played while the program running
# It means that there's a manual action is required.


# Login information
# Note that you have to finish the captcha manually.
email: ''
password: ''

# Tickets date and time
# Enter the date and time you want to book.
date: '8/3'
time: '23:10'

# Tickets selection
# Please enter the amount of ticket you want to book.
imax_adults: 2
imax_students: 0
imax_seniors: 0
imax_disabled: 0

# Seat selection
# Please enter the seat you want to book.
seats:
  - 'G23'
  - 'G24'
  
# Invoice settings (optional)
# Invoice number should start with / and contains 7 character behind.
# Example: /A123456
invoice: ''

# Headless mode
# If you want to run this script in headless mode, please set this to true.
headless: false
"""
                )
    sys.exit()


def read_config():
    """Read config file.

    Check if config file exists, if not, create one.
    if exists, read config file and return config with dict type.

    :rtype: dict
    """
    if not exists('./config.yml'):
        print("Config file not found, create one by default.\nPlease finish filling config.yml")
        with open('config.yml', 'w', encoding="utf8"):
            config_file_generator()

    try:
        with open('config.yml', 'r', encoding="utf8") as f:
            data = yaml.load(f, Loader=SafeLoader)
            config = {
                'email': data['email'],
                'password': data['password'],
                'date': data['date'],
                'time': data['time'],
                'imax_adults': data['imax_adults'],
                'imax_students': data['imax_students'],
                'imax_seniors': data['imax_seniors'],
                'imax_disabled': data['imax_disabled'],
                'seats': data['seats'],
                'invoice': data['invoice'],
                'headless': data['headless']
            }
            config['cn_date'] = config['date'].replace('/', '月') + '日'
            return config
    except (KeyError, TypeError):
        print(
            "An error occurred while reading config.yml, please check if the file is corrected filled.\n"
            "If the problem can't be solved, consider delete config.yml and restart the program.\n")
        sys.exit()


def cookies_file_generator():
    """Generate the template of cookies files"""
    with open('cookies.json', 'w', encoding="utf8") as f:
        f.write("""[
    {
        "name": "__RequestVerificationToken",
        "value": "",
        "domain": "www.miramarcinemas.tw"
    },
    {
        "name": "ASP.NET_SessionId",
        "value": "",
        "domain": "www.miramarcinemas.tw"
    }
]"""
                )
        f.close()
    sys.exit()


def read_cookies():
    """Read cookies file.

    Check if cookies file exists, if not, create one.
    if exists, read cookies file and return cookies with list type.

    :rtype: list
    """
    if not exists('./cookies.json'):
        print(
            "Cookies file not found, generated by default, please restart the program.")
        with open('cookies.json', 'w', encoding="utf8"):
            cookies_file_generator()
        sys.exit()
    try:
        with open('cookies.json', 'r', encoding="utf8") as file:
            cookies = json.loads(file.read())
            file.close()
            return cookies
    except (KeyError, TypeError):
        print(
            "An error occurred while reading cookies.json, please check if the file is corrected filled.\n"
            "If the problem can't be solved, consider delete cookies.json and restart the program.\n")
        sys.exit()


def update_cookies(request_verification_token, asp_net_session_id):
    """Update cookies file.

    Update cookies file with new cookies.

    :param request_verification_token: __RequestVerificationToken
    :param asp_net_session_id: ASP.NET_SessionId
    :rtype: None
    """
    cookies = read_cookies()
    cookies[0]['value'] = request_verification_token
    cookies[1]['value'] = asp_net_session_id
    with open('cookies.json', 'w', encoding="utf8") as file:
        file.write(json.dumps(cookies, indent=4))
        file.close()


def get_seats():
    config = read_config()
    seats = config['seats']
    seat_table = {'A': 2, 'B': 3, 'C': 4, 'D': 5, 'E': 6, 'F': 7, 'G': 8, 'H': 10, 'I': 11, 'J': 12,
                  'K': 13, 'L': 21, 'M': 22}
    seats_list = []
    for seat in seats:
        if seat[0:1] not in seat_table:
            print(f"Seat {seat} is not valid, please fix it in config.yml.")
            sys.exit()
        temp = []
        if int(seat_table[seat[0:1]]) <= 13 and int(seat[1:]) <= 11:
            temp = [seat_table[seat[0:1]], int(seat[1:]), seat]
        elif int(seat_table[seat[0:1]]) <= 13 and 14 <= int(seat[1:]) <= 25:
            temp = [seat_table[seat[0:1]], int(seat[1:]) + 1, seat]
        elif int(seat_table[seat[0:1]]) <= 13 and 28 <= int(seat[1:]) <= 37:
            temp = [seat_table[seat[0:1]], int(seat[1:]) + 2, seat]
        elif int(seat[1:]) >= 21:
            temp = [seat_table[seat[0:1]], int(seat[1:]), seat]
        seats_list.append(temp)
    return seats_list


def play_ding_sound():
    """Play ding sound when manual action is needed."""
    thread = threading.Thread(target=playsound, args=('./ding.wav',))
    thread.start()
